
-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Categories table
create table if not exists public.categories (
  id uuid primary key default uuid_generate_v4(),
  name text not null unique,
  slug text not null unique,
  icon text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Products table
create table if not exists public.products (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  slug text not null unique,
  description text,
  price numeric(10,2) not null,
  image_url text,
  badge text,
  rating numeric(3,2) default 0,
  review_count integer default 0,
  category_id uuid references public.categories(id) on delete set null,
  in_stock boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Product variants (size, color, etc)
create table if not exists public.product_variants (
  id uuid primary key default uuid_generate_v4(),
  product_id uuid not null references public.products(id) on delete cascade,
  name text not null,
  price_adjustment numeric(10,2) default 0,
  stock integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Update trigger for products.updated_at
create or replace function public.update_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists update_products_updated_at on public.products;
create trigger update_products_updated_at
  before update on public.products
  for each row execute function public.update_updated_at();

-- Indexes
create index if not exists idx_products_category on public.products(category_id);
create index if not exists idx_products_slug on public.products(slug);
create index if not exists idx_categories_slug on public.categories(slug);

-- Seed categories
insert into public.categories (name, slug, icon) values
  ('Tech Gear', 'tech-gear', 'laptop_mac'),
  ('Dekorasi Kantor', 'office-decor', 'chair'),
  ('Perangkat Wearable', 'wearables', 'watch'),
  ('Produktivitas', 'productivity', 'auto_stories'),
  ('Pakaian', 'apparel', 'checkroom'),
  ('Kesehatan', 'wellness', 'coffee'),
  ('Kebugaran', 'fitness', 'fitness_center')
on conflict (slug) do nothing;

-- Seed 100 products
insert into public.products (name, slug, description, price, image_url, badge, rating, review_count, category_id, in_stock) values
  (
    'Mouse Wireless Pro',
    'wireless-pro-mouse',
    'Mouse wireless presisi dengan lekuk ergonomis dan teknologi klik senyap. Dilengkapi warna hitam matte dengan pencahayaan RGB aksen yang halus.',
    79.00,
    null,
    'Peringkat Teratas',
    4.7,
    312,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Kursi ErgoLift',
    'ergolift-chair',
    'Kursi kantor ergonomis berprestasi dengan dukungan lumbar adaptif dan anyaman breathable. Dirancang untuk sesi kerja 12 jam.',
    599.00,
    null,
    'Paling Laris',
    4.8,
    892,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Smartwatch Ultra',
    'smart-watch-ultra',
    'Smartwatch fitness premium dengan casing titanium dan layar AMOLED selalu menyala. Tahan air hingga 100 meter.',
    449.00,
    null,
    'Baru',
    4.6,
    567,
    (select id from public.categories where slug = 'wearables'),
    true
  ),
  (
    'Planner Fokus Pro',
    'focus-planner-pro',
    'Buku planner harian berkulit kulit dengan kerangka produktivitas terpandu dan penutup magnet. Dilengkapi spread goal-setting triwulanan.',
    38.00,
    null,
    null,
    4.4,
    203,
    (select id from public.categories where slug = 'productivity'),
    true
  ),
  (
    'Sweater Rajutan Merino',
    'merino-crew-sweater',
    'Sweater wol merino dengan potongan longgar dalam warna charcoal heather. Sentuhan lembut dengan manset rajutan dan bahu jatuh.',
    95.00,
    null,
    null,
    4.3,
    178,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Set Seduh Keramik',
    'ceramic-pour-over-set',
    'Kit seduh kopi minimalis dengan kendi kaca borosilicate dan dripper keramik putih matte. Dapat menyajikan 2-3 cangkir.',
    64.00,
    null,
    'Peringkat Teratas',
    4.8,
    421,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Dumbel Adjustable',
    'adjustable-dumbbells',
    'Pasangan dumbel adjustable hemat tempat dengan sistem berat cepat dari 5 hingga 52.5 lbs. Pegangan grip berlapis karet.',
    349.00,
    null,
    null,
    4.5,
    634,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Keypad Mekanikal',
    'mechanical-keypad',
    'Keypad mekanikal ringkas 16 tombol dengan switch hot-swappable dan frame aluminum CNC. Dapat diprogram melalui firmware open-source.',
    89.00,
    null,
    null,
    4.6,
    291,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Mat Meja XL',
    'desk-mat-xl',
    'Mat meja ekstra besar dalam warna abu-abu gelap dengan tepi jahitan. Permukaan polyurethane tahan air melindungi ruang kerja Anda.',
    42.00,
    null,
    null,
    4.2,
    156,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Dompet Kartu Kulit',
    'leather-card-wallet',
    'Dompet kartu tipis lipat dua dalam kulit cognac full-grain. Dapat menampung hingga 8 kartu dengan kompartemen uang tengah.',
    65.00,
    null,
    null,
    4.1,
    89,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Earbuds Anti-Noise',
    'noise-cancel-earbuds',
    'Earbuds true wireless ringkas dengan pembatalan bising aktif hibrida dan mode transparansi. Baterai 8 jam dengan casing pengisian nirkabel.',
    159.00,
    null,
    'Baru',
    4.4,
    445,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Rangka Meja Berdiri',
    'standing-desk-frame',
    'Rangka meja berdiri elektrik motor ganda dengan preset memori yang dapat diprogram dan sensor anti-tabrakan. Menopang hingga 220 lbs.',
    429.00,
    null,
    null,
    4.7,
    723,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Band Pelacak Kebugaran',
    'fitness-tracker-band',
    'Band kebugaran ringan dengan pemantauan detak jantung berkelanjutan dan pelacakan tidur. Baterai enam bulan dalam sekali pengisian.',
    49.00,
    null,
    null,
    4.0,
    198,
    (select id from public.categories where slug = 'wearables'),
    true
  ),
  (
    'Lampu Meja Minimalis',
    'minimalist-desk-lamp',
    'Lampu meja LED berbentuk skulptural dengan suhu warna yang dapat diatur dan dasar pengisian nirkabel. Konstruksi aluminium anodized.',
    129.00,
    null,
    'Peringkat Teratas',
    4.9,
    876,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Ransel Kanvas',
    'canvas-backpack',
    'Ransel kanvas lapis lilin tahan cuaca dengan kompartemen laptop berlapis dan aksen kulit. Kapasitas 25L untuk perjalanan harian.',
    145.00,
    null,
    null,
    4.3,
    267,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Botol Air Isolasi',
    'insulated-water-bottle',
    'Botol air stainless steel isolasi tiga lapis yang menjaga minuman tetap dingin selama 24 jam atau panas selama 12 jam. Mulut lebar untuk es.',
    34.00,
    null,
    null,
    4.6,
    1023,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Set Ban Resistansi',
    'resistance-band-set',
    'Set lima ban resistansi loop dengan jangkar pintu dan tali pergelangan kaki. Resistensi bertingkat dari ringan hingga ekstra berat.',
    29.00,
    null,
    null,
    4.2,
    534,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Pad Pengisian Nirkabel',
    'wireless-charging-pad',
    'Pad pengisian nirkabel cepat dengan output 15W dan deteksi benda asing. Kompatibel dengan semua perangkat berkemampuan Qi.',
    39.00,
    null,
    null,
    4.1,
    312,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Kemeja Linen',
    'linen-button-down',
    'Kemeja linen button-down longgar dalam warna oat alami. Kain breathable yang sempurna untuk layering musim panas atau hari santai.',
    88.00,
    null,
    null,
    4.4,
    145,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Bantal Meditasi',
    'meditation-cushion',
    'Bantal meditasi gaya zafu berisi sekam buckwheat organik. Sarung dapat dilepas dan dicuci mesin dalam warna abu-abu batu.',
    58.00,
    null,
    null,
    4.5,
    289,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Timbangan Cerdas',
    'smart-scale',
    'Timbangan komposisi tubuh cerdas dengan 14 pengukuran biometrik dan sinkronisasi aplikasi. Bagian atas kaca tempered elegan dengan layar tersembunyi.',
    49.00,
    null,
    'Paling Laris',
    4.6,
    1456,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Monitor Portabel',
    'portable-monitor',
    'Monitor USB-C portabel 15,6 inci dengan panel IPS 1080p dan kickstand bawaan. Sempurna untuk produktivitas layar ganda saat bepergian.',
    249.00,
    null,
    null,
    4.5,
    678,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Syal Campuran Wol',
    'wool-blend-scarf',
    'Syal campuran wol abadi dalam warna kamel dengan tepi gulung tangan. Panjang ekstra untuk berbagai pilihan gaya.',
    55.00,
    null,
    null,
    4.3,
    167,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Mat Yoga Premium',
    'yoga-mat-premium',
    'Mat yoga premium setebal 6mm dengan penanda alignment dan tekstur anti-slip. Terbuat dari bahan TPE ramah lingkungan.',
    68.00,
    null,
    'Peringkat Teratas',
    4.7,
    934,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Set Pena Emas',
    'pen-set-gold',
    'Set tiga pena bolpoin isi ulang dengan aksen berlapis emas dan tinta gel hitam. Hadir dalam kotak hadiah magnetik.',
    45.00,
    null,
    null,
    4.4,
    223,
    (select id from public.categories where slug = 'productivity'),
    true
  ),
  (
    'Speaker Bluetooth',
    'bluetooth-speaker',
    'Speaker Bluetooth portabel dengan suara 360 derajat dan baterai 20 jam. Tahan air IP67 untuk petualangan luar ruangan.',
    79.00,
    null,
    null,
    4.3,
    567,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Stand Monitor Riser',
    'monitor-stand-riser',
    'Stand monitor riser bambu solid dengan laci penyimpanan untuk keyboard dan perlengkapan kantor. Dilengkapi lubang manajemen kabel.',
    54.00,
    null,
    null,
    4.5,
    389,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Jogger Chino',
    'chino-joggers',
    'Interpretasi modern chino klasik dengan gaya jogger meruncing. Twill katun stretch dengan pinggang elastis dan saku beritsleting.',
    78.00,
    null,
    null,
    4.2,
    234,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Difuser Minyak Esensial',
    'essential-oil-diffuser',
    'Difuser minyak esensial ultrasonik minimalis dengan pencahayaan ambient. Operasi senyap untuk kamar tidur dan kantor.',
    34.00,
    null,
    null,
    4.6,
    445,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Roller Busa',
    'foam-roller',
    'Roller busa berdensitas tinggi dengan permukaan bertekstur untuk pijat jaringan dalam. Panjang 18 inci dengan inti padat.',
    28.00,
    null,
    null,
    4.4,
    789,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Hub USB-C 7-dalam-1',
    'usb-c-hub-7-in-1',
    'Hub USB-C aluminium ringkas dengan HDMI 4K, pembaca kartu SD, dan tiga port USB-A. Plug-and-play tanpa perlu driver.',
    59.00,
    null,
    null,
    4.5,
    1234,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Kaos Polo Klasik',
    'polo-shirt-classic',
    'Kaos polo pique potongan klasik dalam warna navy dengan kancing mother-of-pearl. Katun pra-susut dengan kerah yang diperkuat.',
    65.00,
    null,
    null,
    4.1,
    312,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Selimut Berpemberat',
    'weighted-blanket',
    'Selimut berpemberat 15 pon dengan isian manik kaca dan sarung katun breathable. Mendorong tidur lebih nyenyak dan mengurangi kecemasan.',
    89.00,
    null,
    'Paling Laris',
    4.8,
    1567,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Set Buku Catatan A5',
    'notebook-set-a5',
    'Set tiga buku catatan A5 bertitik dengan kertas 180gsm dan jilid lay-flat. Ideal untuk journaling dan bullet journaling.',
    24.00,
    null,
    null,
    4.5,
    678,
    (select id from public.categories where slug = 'productivity'),
    true
  ),
  (
    'Jaket Denim',
    'denim-jacket',
    'Jaket denim klasik dengan potongan slim modern. Dilengkapi saku dada, penutup kancing, dan detail selvedge.',
    128.00,
    null,
    null,
    4.3,
    145,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Ban Resistansi',
    'resistance-bands',
    'Set lima ban resistansi loop dengan jangkar pintu dan tali pergelangan kaki. Resistensi bertingkat dari ringan hingga ekstra berat.',
    29.00,
    null,
    null,
    4.2,
    534,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Bohlam Pintar',
    'smart-light-bulb',
    'Bohlam pintar Wi-Fi dengan 16 juta warna dan cahaya putih yang dapat disetel. Kompatibel suara dengan Alexa dan Google Assistant.',
    19.00,
    null,
    null,
    4.0,
    2345,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Buku Kulit',
    'leather-notebook',
    'Buku catatan bersampul kulit buatan tangan dengan kertas isi ulang. Menua dengan indah membentuk patina yang kaya seiring waktu.',
    48.00,
    null,
    null,
    4.6,
    289,
    (select id from public.categories where slug = 'productivity'),
    true
  ),
  (
    'Lompat Tali Speed',
    'jump-rope-speed',
    'Lompat tali speed profesional dengan ball bearing dan panjang tali yang dapat disesuaikan. Pegangan aluminium ringan.',
    22.00,
    null,
    null,
    4.4,
    567,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Keyboard Mekanikal',
    'mechanical-keyboard',
    'Keyboard mekanikal 75% ringkas dengan switch hot-swappable dan pencahayaan RGB per tombol. Konektivitas USB-C dengan keycap PBT.',
    149.00,
    null,
    'Peringkat Teratas',
    4.7,
    890,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Organizer Meja',
    'desk-organizer',
    'Organizer meja modular dengan kompartemen untuk pena, sticky notes, dan ponsel. Terbuat dari bambu berkelanjutan.',
    42.00,
    null,
    null,
    4.3,
    345,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Hoodie Katun',
    'cotton-hoodie',
    'Hoodie katun tebal dengan potongan longgar dan interior brushed. Dilengkapi saku kanguru dan manset ribbed.',
    89.00,
    null,
    null,
    4.5,
    678,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Pembersih Udara Mini',
    'air-purifier-mini',
    'Pembersih udara HEPA ringkas untuk meja dan ruangan kecil. Menghilangkan 99,97% partikel udara dengan operasi senyap.',
    79.00,
    null,
    null,
    4.4,
    456,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Roller Pergelangan Tangan',
    'wrist-roller',
    'Alat latih lengan bawah dengan pelat beban yang dapat disesuaikan dan pegangan anti-slip. Membangun kekuatan genggaman dan daya tahan pergelangan tangan.',
    18.00,
    null,
    null,
    4.1,
    123,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Stand Papan Tulis',
    'whiteboard-stand',
    'Stand papan tulis portabel dengan ketinggian yang dapat diatur dan nampan spidol. Sempurna untuk kantor rumahan dan ruang kelas.',
    65.00,
    null,
    null,
    4.2,
    234,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Sepatu Lari',
    'running-shoes',
    'Sepatu lari ringan dengan bantalan responsif dan upper mesh breathable. Dirancang untuk latihan harian di jalan dan lintasan.',
    129.00,
    null,
    'Baru',
    4.6,
    789,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Botol Infuser Teh',
    'tea-infuser-bottle',
    'Botol teh kaca dinding ganda dengan infuser stainless steel bawaan. Menjaga teh tetap panas selama berjam-jam dan muat di cup holder mobil.',
    26.00,
    null,
    null,
    4.5,
    345,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Mat Mouse Ergonomis',
    'ergonomic-mouse-pad',
    'Mat mouse ergonomis berisi gel dengan penyangga pergelangan tangan. Alas anti-slip dan permukaan tracking halus untuk kontrol presisi.',
    19.00,
    null,
    null,
    4.3,
    567,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Tas Kanvas',
    'canvas-tote-bag',
    'Tas tote kanvas tugas berat dengan jahitan diperkuat dan saku interior. Sempurna untuk belanjaan, buku, atau perlengkapan pantai.',
    32.00,
    null,
    null,
    4.4,
    890,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Kettlebell 16kg',
    'kettlebell-16kg',
    'Kettlebell besi cor dengan lapisan powder-coat halus dan pegangan lebar. Sempurna untuk swing, squat, dan Turkish get-up.',
    65.00,
    null,
    null,
    4.6,
    456,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Kamera Web 4K',
    'webcam-4k',
    'Kamera web 4K dengan fokus otomatis, ring light bawaan, dan dua mikrofon peredam bising. Termasuk dudukan klip atau stand.',
    99.00,
    null,
    null,
    4.5,
    1234,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Dasi Sutra',
    'silk-tie',
    'Dasi sutra murni dengan tepi finishing tangan dan pola herringbone halus. Tambahan serbaguna untuk lemari profesional mana pun.',
    48.00,
    null,
    null,
    4.2,
    167,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Masker Tidur',
    'sleep-mask',
    'Masker tidur sutra berkontur yang menghalangi cahaya tanpa menekan mata. Tali dapat disesuaikan dan dapat dicuci mesin.',
    24.00,
    null,
    null,
    4.7,
    2345,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Tabung Resistansi',
    'resistance-tubes',
    'Set lima tabung resistansi dengan jangkar pintu, pegangan, dan tali pergelangan kaki. Ideal untuk latihan seluruh tubuh di mana saja.',
    35.00,
    null,
    null,
    4.3,
    678,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Keyboard Nirkabel',
    'wireless-keyboard',
    'Keyboard nirkabel ramping dengan tombol mekanisme gunting dan pairing Bluetooth multi-perangkat. Baterai isi ulang dengan daya tahan 90 hari.',
    69.00,
    null,
    null,
    4.4,
    567,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Stand Laptop',
    'laptop-stand',
    'Stand laptop aluminium yang dapat disesuaikan dengan lubang ventilasi. Mengangkat layar setinggi mata untuk postur lebih baik.',
    59.00,
    null,
    null,
    4.6,
    890,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Celana Jogger',
    'jogger-pants',
    'Celana jogger meruncing dengan pinggang elastis dan saku beritsleting. Terbuat dari campuran katun stretch untuk kenyamanan sepanjang hari.',
    54.00,
    null,
    null,
    4.2,
    345,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Bola Pijat',
    'massage-ball',
    'Bola pijat bertekstur untuk pelepasan titik pemicu dan pelepasan myofascial. Ukuran ringkas sempurna untuk bepergian.',
    16.00,
    null,
    null,
    4.5,
    1234,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Buku Catatan Kulit',
    'notebook-leather',
    'Buku catatan bersampul kulit buatan tangan dengan kertas isi ulang. Menua dengan indah membentuk patina yang kaya seiring waktu.',
    48.00,
    null,
    null,
    4.6,
    289,
    (select id from public.categories where slug = 'productivity'),
    true
  ),
  (
    'Powerbank 20000',
    'power-bank-20000',
    'Powerbank berkapasitas tinggi 20000mAh dengan dua port USB-C. Mengisi laptop, tablet, dan ponsel secara bersamaan.',
    59.00,
    null,
    null,
    4.4,
    1567,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Beanie Wol',
    'wool-beanie',
    'Beanie wol merino rajutan halus dengan lipatan cuff. Lembut, hangat, dan breathable untuk layering cuaca dingin.',
    32.00,
    null,
    null,
    4.3,
    234,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Palang Pull-Up',
    'pull-up-bar',
    'Palang pull-up pintu dengan posisi multi-grip dan pegangan berbantal. Menopang hingga 300 lbs dengan mekanisme penguncian aman.',
    45.00,
    null,
    null,
    4.5,
    890,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Stand Tablet',
    'tablet-stand',
    'Stand tablet aluminium serbaguna dengan sudut pandang yang dapat disesuaikan. Kompatibel dengan tablet 7 hingga 13 inci.',
    39.00,
    null,
    null,
    4.4,
    567,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Kaos Grafis',
    'graphic-tee',
    'Kaos grafis katun tebal dengan potongan longgar. Kain pra-susut dengan tekstur lembut.',
    35.00,
    null,
    null,
    4.1,
    456,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Lilin Aromaterapi',
    'aromatherapy-candle',
    'Lilin aromaterapi lilin kedelai dengan minyak esensial lavender dan eukaliptus. Terbakar bersih selama 50 jam.',
    28.00,
    null,
    null,
    4.6,
    1234,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Roller Perut',
    'ab-roller',
    'Roller perut dengan alas lutut dan pegangan anti-slip. Menargetkan otot inti untuk latihan perut yang efektif.',
    22.00,
    null,
    null,
    4.3,
    678,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Mouse Wireless',
    'mouse-wireless',
    'Mouse wireless presisi dengan lekuk ergonomis dan teknologi klik senyap. Dilengkapi warna hitam matte dengan pencahayaan RGB aksen yang halus.',
    79.00,
    null,
    null,
    4.7,
    312,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Pad Meja',
    'desk-pad',
    'Pad meja extended dengan permukaan micro-weave halus dan alas karet anti-slip. Melindungi meja Anda dan menyediakan ruang mouse yang luas.',
    29.00,
    null,
    null,
    4.5,
    890,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Celana Pendek Chino',
    'chino-shorts',
    'Celana pendek chino klasik dengan mid-rise nyaman dan inseam 9 inci. Twill katun stretch dengan lubang sabuk dan saku beritsleting.',
    58.00,
    null,
    null,
    4.2,
    234,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Tas Hidrasi',
    'hydration-pack',
    'Tas hidrasi ringan dengan reservoir 2 liter dan tali yang dapat disesuaikan. Ideal untuk lari, hiking, dan bersepeda.',
    65.00,
    null,
    null,
    4.4,
    567,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Light Bar Monitor',
    'monitor-light-bar',
    'Light bar monitor yang dipasang di layar dengan kecerahan dan suhu warna yang dapat diatur. Mengurangi silau dan kelelahan mata.',
    89.00,
    null,
    null,
    4.6,
    789,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Kemeja Slim',
    'dress-shirt-slim',
    'Kemeja slim-fit anti-setrika dalam warna biru muda. Katun anti-kusut dengan kerah spread dan manset French.',
    85.00,
    null,
    null,
    4.3,
    345,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Roller Busa Lembut',
    'foam-roller-soft',
    'Roller busa berdensitas lembut untuk pemulihan otot ringan dan latihan fleksibilitas. Panjang 18 inci dengan permukaan bertekstur.',
    24.00,
    null,
    null,
    4.2,
    456,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Buku Catatan Dot Grid',
    'notebook-dot-grid',
    'Buku catatan A5 dot grid dengan 160 halaman dan jilid lay-flat. Sempurna untuk bullet journaling dan sketsa.',
    18.00,
    null,
    null,
    4.5,
    1234,
    (select id from public.categories where slug = 'productivity'),
    true
  ),
  (
    'Earbuds Nirkabel',
    'wireless-earbuds',
    'Earbuds true wireless ringkas dengan bass dalam dan total baterai 24 jam. Tahan air IPX5 untuk olahraga.',
    89.00,
    null,
    null,
    4.4,
    2345,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Keyboard Bambu',
    'bamboo-keyboard',
    'Keyboard nirkabel ramping dengan aksen bambu dan tombol low-profile. Desain ramah lingkungan dengan pairing multi-perangkat.',
    99.00,
    null,
    'Baru',
    4.6,
    189,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Kardigan Wol',
    'wool-cardigan',
    'Kardigan wol merino potongan longgar dengan kancing tanduk dan saku tempel. Sempurna untuk layering di cuaca sejuk.',
    165.00,
    null,
    null,
    4.7,
    312,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Lompat Tali',
    'jump-rope',
    'Lompat tali speed profesional dengan ball bearing dan panjang tali yang dapat disesuaikan. Pegangan aluminium ringan.',
    22.00,
    null,
    null,
    4.4,
    567,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Balok Yoga',
    'yoga-block',
    'Balok yoga busa EVA berdensitas tinggi dengan tepi miring. Memberikan dukungan dan stabilitas untuk peregangan lebih dalam.',
    16.00,
    null,
    null,
    4.5,
    890,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Kacamata Hitam Polarized',
    'sunglasses-polarized',
    'Kacamata hitam polarized dengan frame titanium ringan dan perlindungan UV400. Gaya aviator klasik untuk penggunaan sehari-hari.',
    125.00,
    null,
    null,
    4.3,
    456,
    (select id from public.categories where slug = 'wearables'),
    true
  ),
  (
    'Sabuk Kulit',
    'leather-belt',
    'Sabuk kulit full-grain dengan gesper perak brushed. Buatan tangan dengan jahitan presisi dan desain abadi.',
    55.00,
    null,
    null,
    4.6,
    789,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Ketel Elektrik',
    'electric-kettle',
    'Ketel elektrik suhu variabel dengan fungsi tahan panas dan leher angsa. Sempurna untuk kopi pour-over dan teh.',
    79.00,
    null,
    null,
    4.7,
    1234,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Alat Latih Genggaman',
    'grip-trainer',
    'Alat latih genggaman resistensi variabel dengan dial yang dapat disesuaikan. Membangun kekuatan tangan dan lengan bawah untuk panjat tebing dan aktivitas harian.',
    19.00,
    null,
    null,
    4.4,
    567,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Sarung Laptop',
    'laptop-sleeve',
    'Sarung laptop neoprene berbantal dengan lapisan faux-fur. Melindungi dari goresan dan benturan ringan dengan profil ramping.',
    39.00,
    null,
    null,
    4.5,
    890,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Celana Pendek Lari',
    'running-shorts',
    'Celana pendek lari ringan dengan lapisan brief bawaan dan saku beritsleting. Kain penyerap keringat dengan detail reflektif.',
    45.00,
    null,
    null,
    4.3,
    345,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Lilin Wangi',
    'scented-candle',
    'Lilin lilin kedelai tuangan tangan dengan aroma cedar dan bergamot. Dikemas dalam wadah keramik yang dapat digunakan kembali.',
    32.00,
    null,
    null,
    4.6,
    1234,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Kettlebell 24kg',
    'kettlebell-24kg',
    'Kettlebell besi cor dengan lapisan powder-coat halus dan pegangan lebar. Sempurna untuk latihan kekuatan tingkat lanjut.',
    89.00,
    null,
    null,
    4.7,
    456,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Mikrofon USB',
    'microphone-usb',
    'Mikrofon kondensor USB profesional dengan pola pickup cardioid dan pop filter bawaan. Sempurna untuk streaming dan podcasting.',
    129.00,
    null,
    null,
    4.8,
    789,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Syal Wol',
    'wool-scarf',
    'Syal campuran wol abadi dalam warna kamel dengan tepi gulung tangan. Panjang ekstra untuk berbagai pilihan gaya.',
    55.00,
    null,
    null,
    4.3,
    167,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Bangku Meditasi',
    'meditation-bench',
    'Bangku meditasi lipat dengan dudukan miring dan bantal empuk. Mendukung duduk bersila dengan nyaman.',
    78.00,
    null,
    null,
    4.5,
    234,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Powerbank',
    'power-bank',
    'Powerbank ringkas dengan kapasitas 10000mAh dan pengisian cepat. Muat mudah di saku atau tas untuk pengisian saat bepergian.',
    29.00,
    null,
    null,
    4.3,
    2345,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Chino Slim',
    'chinos-slim',
    'Celana chino slim-fit dalam warna batu dengan stretch nyaman. Potongan modern dengan mid-rise dan kaki lurus.',
    72.00,
    null,
    null,
    4.4,
    567,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Roller Busa Sedang',
    'foam-roller-medium',
    'Roller busa berdensitas sedang untuk pemulihan otot umum. Panjang 18 inci dengan permukaan halus.',
    20.00,
    null,
    null,
    4.3,
    890,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Buku Catatan Saku',
    'pocket-notebook',
    'Buku catatan ukuran saku ringkas dengan 192 halaman kertas bertitik. Muat di saku jeans untuk catatan saat bepergian.',
    12.00,
    null,
    null,
    4.4,
    1234,
    (select id from public.categories where slug = 'productivity'),
    true
  ),
  (
    'Steker Pintar',
    'smart-plug',
    'Steker pintar Wi-Fi dengan pemantauan energi dan penjadwalan. Bekerja dengan Alexa dan Google Assistant untuk kontrol suara.',
    15.00,
    null,
    'Paling Laris',
    4.5,
    4567,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Kemeja Denim',
    'denim-shirt',
    'Kemeja denim klasik dengan potongan modern. Dilengkapi saku dada, penutup kancing, dan detail selvedge.',
    78.00,
    null,
    null,
    4.2,
    234,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Sepatu Lari Trail',
    'running-shoes-trail',
    'Sepatu lari trail dengan tapak agresif dan perlindungan rock plate. Membran tahan air untuk kepercayaan diri di segala medan.',
    149.00,
    null,
    null,
    4.6,
    567,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Set Teh',
    'tea-set',
    'Set teh keramik minimalis dengan teko dan empat cangkir. Finishing matte dalam warna putih hangat dengan tekstur halus.',
    85.00,
    null,
    null,
    4.7,
    189,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Keyboard Ergonomis',
    'ergonomic-keyboard',
    'Keyboard ergonomis split dengan tenting yang dapat disesuaikan dan kemiringan negatif. Mengurangi ketegangan pergelangan tangan saat mengetik lama.',
    179.00,
    null,
    'Baru',
    4.6,
    345,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Portofolio Kulit',
    'leather-portfolio',
    'Portofolio kulit mewah dengan organizer dokumen dan sarung tablet. Buatan tangan dari kulit Italia full-grain.',
    185.00,
    null,
    null,
    4.8,
    234,
    (select id from public.categories where slug = 'productivity'),
    true
  )
on conflict (slug) do nothing;

-- RLS policies (disabled for anon key, enable if using auth)
alter table public.categories disable row level security;
alter table public.products disable row level security;
alter table public.product_variants disable row level security;
