
-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Categories table
create table if not exists public.categories (
  id uuid primary key default uuid_generate_v4(),
  name text not null unique,
  slug text not null unique,
  icon text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Products table
create table if not exists public.products (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  slug text not null unique,
  description text,
  price numeric(10,2) not null,
  image_url text,
  badge text,
  rating numeric(3,2) default 0,
  review_count integer default 0,
  category_id uuid references public.categories(id) on delete set null,
  in_stock boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Product variants (size, color, etc)
create table if not exists public.product_variants (
  id uuid primary key default uuid_generate_v4(),
  product_id uuid not null references public.products(id) on delete cascade,
  name text not null,
  price_adjustment numeric(10,2) default 0,
  stock integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Update trigger for products.updated_at
create or replace function public.update_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists update_products_updated_at on public.products;
create trigger update_products_updated_at
  before update on public.products
  for each row execute function public.update_updated_at();

-- Indexes
create index if not exists idx_products_category on public.products(category_id);
create index if not exists idx_products_slug on public.products(slug);
create index if not exists idx_categories_slug on public.categories(slug);

-- Seed categories
insert into public.categories (name, slug, icon) values
  ('Tech Gear', 'tech-gear', 'laptop_mac'),
  ('Office Decor', 'office-decor', 'chair'),
  ('Wearables', 'wearables', 'watch'),
  ('Productivity', 'productivity', 'auto_stories'),
  ('Apparel', 'apparel', 'checkroom'),
  ('Wellness', 'wellness', 'coffee'),
  ('Fitness', 'fitness', 'fitness_center')
on conflict (slug) do nothing;

-- Seed 100 products
insert into public.products (name, slug, description, price, image_url, badge, rating, review_count, category_id, in_stock) values
  (
    'Wireless Pro Mouse',
    'wireless-pro-mouse',
    'A precision wireless mouse with ergonomic curves and silent click technology. Finished in matte black with subtle RGB accent lighting.',
    79.00,
    null,
    'Top Rated',
    4.7,
    312,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'ErgoLift Chair',
    'ergolift-chair',
    'An award-winning ergonomic office chair with adaptive lumbar support and breathable mesh. Designed for 12-hour work sessions.',
    599.00,
    null,
    'Best Seller',
    4.8,
    892,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Smart Watch Ultra',
    'smart-watch-ultra',
    'A premium fitness smartwatch with titanium casing and always-on AMOLED display. Water resistant to 100 meters.',
    449.00,
    null,
    'New',
    4.6,
    567,
    (select id from public.categories where slug = 'wearables'),
    true
  ),
  (
    'Focus Planner Pro',
    'focus-planner-pro',
    'A leather-bound daily planner with guided productivity frameworks and magnetic closure. Includes quarterly goal-setting spreads.',
    38.00,
    null,
    null,
    4.4,
    203,
    (select id from public.categories where slug = 'productivity'),
    true
  ),
  (
    'Merino Crew Sweater',
    'merino-crew-sweater',
    'A relaxed-fit merino wool sweater in heather charcoal. Soft hand-feel with ribbed cuffs and dropped shoulders.',
    95.00,
    null,
    null,
    4.3,
    178,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Ceramic Pour-Over Set',
    'ceramic-pour-over-set',
    'A minimalist pour-over coffee kit with borosilicate glass carafe and matte white ceramic dripper. Serves 2-3 cups.',
    64.00,
    null,
    'Top Rated',
    4.8,
    421,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Adjustable Dumbbells',
    'adjustable-dumbbells',
    'A space-saving adjustable dumbbell pair with quick-select weight system from 5 to 52.5 lbs. Rubberized grip handles.',
    349.00,
    null,
    null,
    4.5,
    634,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Mechanical Keypad',
    'mechanical-keypad',
    'A compact 16-key mechanical keypad with hot-swappable switches and CNC aluminum frame. Programmable via open-source firmware.',
    89.00,
    null,
    null,
    4.6,
    291,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Desk Mat XL',
    'desk-mat-xl',
    'An extra-large extended desk mat in dark gray with stitched edges. Water-resistant polyurethane surface protects your workspace.',
    42.00,
    null,
    null,
    4.2,
    156,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Leather Card Wallet',
    'leather-card-wallet',
    'A slim bifold card wallet in full-grain cognac leather. Holds up to 8 cards with a centered bill compartment.',
    65.00,
    null,
    null,
    4.1,
    89,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Noise-Cancel Earbuds',
    'noise-cancel-earbuds',
    'Compact true wireless earbuds with hybrid active noise cancellation and transparency mode. 8-hour battery with wireless charging case.',
    159.00,
    null,
    'New',
    4.4,
    445,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Standing Desk Frame',
    'standing-desk-frame',
    'A dual-motor electric standing desk frame with programmable memory presets and anti-collision sensors. Supports up to 220 lbs.',
    429.00,
    null,
    null,
    4.7,
    723,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Fitness Tracker Band',
    'fitness-tracker-band',
    'A lightweight fitness band with continuous heart rate monitoring and sleep tracking. Six-month battery life on a single charge.',
    49.00,
    null,
    null,
    4.0,
    198,
    (select id from public.categories where slug = 'wearables'),
    true
  ),
  (
    'Minimalist Desk Lamp',
    'minimalist-desk-lamp',
    'A sculptural LED desk lamp with adjustable color temperature and wireless charging base. Anodized aluminum construction.',
    129.00,
    null,
    'Top Rated',
    4.9,
    876,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Canvas Backpack',
    'canvas-backpack',
    'A weather-resistant waxed canvas backpack with padded laptop compartment and leather trim. 25L capacity for daily commute.',
    145.00,
    null,
    null,
    4.3,
    267,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Insulated Water Bottle',
    'insulated-water-bottle',
    'A triple-insulated stainless steel water bottle that keeps drinks cold for 24 hours or hot for 12 hours. Wide mouth for ice.',
    34.00,
    null,
    null,
    4.6,
    1023,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Resistance Band Set',
    'resistance-band-set',
    'A set of five loop resistance bands with door anchor and ankle straps. Gradient resistance from light to extra heavy.',
    29.00,
    null,
    null,
    4.2,
    534,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Wireless Charging Pad',
    'wireless-charging-pad',
    'A fast wireless charging pad with 15W output and foreign object detection. Compatible with all Qi-enabled devices.',
    39.00,
    null,
    null,
    4.1,
    312,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Linen Button-Down',
    'linen-button-down',
    'A relaxed linen button-down shirt in natural oat. Breathable fabric perfect for summer layering or casual Fridays.',
    88.00,
    null,
    null,
    4.4,
    145,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Meditation Cushion',
    'meditation-cushion',
    'A zafu-style meditation cushion filled with organic buckwheat hulls. Removable machine-washable cover in stone gray.',
    58.00,
    null,
    null,
    4.5,
    289,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Smart Scale',
    'smart-scale',
    'A body composition smart scale with 14 biometric measurements and app sync. Sleek tempered glass top with hidden display.',
    49.00,
    null,
    'Best Seller',
    4.6,
    1456,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Portable Monitor',
    'portable-monitor',
    'A 15.6-inch portable USB-C monitor with 1080p IPS panel and built-in kickstand. Perfect for dual-screen productivity on the go.',
    249.00,
    null,
    null,
    4.5,
    678,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Wool Blend Scarf',
    'wool-blend-scarf',
    'A timeless wool-blend scarf in camel with hand-rolled edges. Generous length for multiple styling options.',
    55.00,
    null,
    null,
    4.3,
    167,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Yoga Mat Premium',
    'yoga-mat-premium',
    'A 6mm thick premium yoga mat with alignment markers and non-slip texture. Made from eco-friendly TPE material.',
    68.00,
    null,
    'Top Rated',
    4.7,
    934,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Pen Set Gold',
    'pen-set-gold',
    'A set of three retractable ballpoint pens with gold-plated accents and black gel ink. Comes in a magnetic gift box.',
    45.00,
    null,
    null,
    4.4,
    223,
    (select id from public.categories where slug = 'productivity'),
    true
  ),
  (
    'Bluetooth Speaker',
    'bluetooth-speaker',
    'A portable Bluetooth speaker with 360-degree sound and 20-hour battery life. IP67 waterproof for outdoor adventures.',
    79.00,
    null,
    null,
    4.3,
    567,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Monitor Stand Riser',
    'monitor-stand-riser',
    'A solid bamboo monitor stand riser with storage drawer for keyboard and office supplies. Cable management cutouts included.',
    54.00,
    null,
    null,
    4.5,
    389,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Chino Joggers',
    'chino-joggers',
    'A modern take on the classic chino with tapered jogger styling. Stretch cotton twill with elastic waistband and zippered pockets.',
    78.00,
    null,
    null,
    4.2,
    234,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Essential Oil Diffuser',
    'essential-oil-diffuser',
    'A minimalist ultrasonic essential oil diffuser with ambient lighting. Whisper-quiet operation for bedrooms and offices.',
    34.00,
    null,
    null,
    4.6,
    445,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Foam Roller',
    'foam-roller',
    'A high-density foam roller with textured surface for deep tissue massage. 18 inches long with a solid core.',
    28.00,
    null,
    null,
    4.4,
    789,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'USB-C Hub 7-in-1',
    'usb-c-hub-7-in-1',
    'A compact aluminum USB-C hub with HDMI 4K, SD card reader, and three USB-A ports. Plug-and-play with no drivers needed.',
    59.00,
    null,
    null,
    4.5,
    1234,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Polo Shirt Classic',
    'polo-shirt-classic',
    'A classic-fit pique polo shirt in navy with mother-of-pearl buttons. Pre-shrunk cotton with reinforced collar.',
    65.00,
    null,
    null,
    4.1,
    312,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Weighted Blanket',
    'weighted-blanket',
    'A 15-pound weighted blanket with glass bead filling and breathable cotton cover. Promotes deeper sleep and reduces anxiety.',
    89.00,
    null,
    'Best Seller',
    4.8,
    1567,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Notebook Set A5',
    'notebook-set-a5',
    'A set of three A5 dotted notebooks with 180gsm paper and lay-flat binding. Ideal for journaling and bullet journaling.',
    24.00,
    null,
    null,
    4.5,
    678,
    (select id from public.categories where slug = 'productivity'),
    true
  ),
  (
    'Denim Jacket',
    'denim-jacket',
    'A classic denim jacket with a modern slim fit. Features chest pockets, button closure, and selvedge detail.',
    128.00,
    null,
    null,
    4.3,
    145,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Resistance Bands',
    'resistance-bands',
    'A set of five loop resistance bands with door anchor and ankle straps. Gradient resistance from light to extra heavy.',
    29.00,
    null,
    null,
    4.2,
    534,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Smart Light Bulb',
    'smart-light-bulb',
    'A Wi-Fi enabled smart bulb with 16 million colors and tunable white light. Voice compatible with Alexa and Google Assistant.',
    19.00,
    null,
    null,
    4.0,
    2345,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Leather Notebook',
    'leather-notebook',
    'A handcrafted leather-bound notebook with refillable paper. Ages beautifully with a rich patina over time.',
    48.00,
    null,
    null,
    4.6,
    289,
    (select id from public.categories where slug = 'productivity'),
    true
  ),
  (
    'Jump Rope Speed',
    'jump-rope-speed',
    'A professional speed jump rope with ball bearings and adjustable cable length. Lightweight aluminum handles.',
    22.00,
    null,
    null,
    4.4,
    567,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Mechanical Keyboard',
    'mechanical-keyboard',
    'A compact 75% mechanical keyboard with hot-swappable switches and per-key RGB lighting. USB-C connectivity with PBT keycaps.',
    149.00,
    null,
    'Top Rated',
    4.7,
    890,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Desk Organizer',
    'desk-organizer',
    'A modular desktop organizer with compartments for pens, sticky notes, and phone. Made from sustainable bamboo.',
    42.00,
    null,
    null,
    4.3,
    345,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Cotton Hoodie',
    'cotton-hoodie',
    'A heavyweight cotton hoodie with a relaxed fit and brushed interior. Features kangaroo pocket and ribbed cuffs.',
    89.00,
    null,
    null,
    4.5,
    678,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Air Purifier Mini',
    'air-purifier-mini',
    'A compact HEPA air purifier for desks and small rooms. Removes 99.97% of airborne particles with whisper-quiet operation.',
    79.00,
    null,
    null,
    4.4,
    456,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Wrist Roller',
    'wrist-roller',
    'A forearm trainer with adjustable weight plate and non-slip handles. Builds grip strength and wrist endurance.',
    18.00,
    null,
    null,
    4.1,
    123,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Whiteboard Stand',
    'whiteboard-stand',
    'A portable whiteboard stand with adjustable height and marker tray. Perfect for home offices and classrooms.',
    65.00,
    null,
    null,
    4.2,
    234,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Running Shoes',
    'running-shoes',
    'Lightweight running shoes with responsive cushioning and breathable mesh upper. Designed for daily training on roads and tracks.',
    129.00,
    null,
    'New',
    4.6,
    789,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Tea Infuser Bottle',
    'tea-infuser-bottle',
    'A double-wall glass tea bottle with built-in stainless steel infuser. Keeps tea hot for hours and fits in car cup holders.',
    26.00,
    null,
    null,
    4.5,
    345,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Ergonomic Mouse Pad',
    'ergonomic-mouse-pad',
    'A gel-filled ergonomic mouse pad with wrist support. Non-slip base and smooth tracking surface for precise control.',
    19.00,
    null,
    null,
    4.3,
    567,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Canvas Tote Bag',
    'canvas-tote-bag',
    'A heavy-duty canvas tote bag with reinforced stitching and interior pocket. Perfect for groceries, books, or beach essentials.',
    32.00,
    null,
    null,
    4.4,
    890,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Kettlebell 16kg',
    'kettlebell-16kg',
    'A cast iron kettlebell with a smooth powder-coat finish and wide handle. Perfect for swings, squats, and Turkish get-ups.',
    65.00,
    null,
    null,
    4.6,
    456,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Webcam 4K',
    'webcam-4k',
    'A 4K webcam with auto-focus, built-in ring light, and noise-reducing dual microphones. Clip-on or stand mount included.',
    99.00,
    null,
    null,
    4.5,
    1234,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Silk Tie',
    'silk-tie',
    'A pure silk tie with hand-finished edges and a subtle herringbone pattern. A versatile addition to any professional wardrobe.',
    48.00,
    null,
    null,
    4.2,
    167,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Sleep Mask',
    'sleep-mask',
    'A contoured silk sleep mask that blocks light without pressure on the eyes. Adjustable strap and machine washable.',
    24.00,
    null,
    null,
    4.7,
    2345,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Resistance Tubes',
    'resistance-tubes',
    'A set of five resistance tubes with door anchor, handles, and ankle straps. Ideal for full-body workouts anywhere.',
    35.00,
    null,
    null,
    4.3,
    678,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Wireless Keyboard',
    'wireless-keyboard',
    'A slim wireless keyboard with scissor mechanism keys and multi-device Bluetooth pairing. Rechargeable with 90-day battery life.',
    69.00,
    null,
    null,
    4.4,
    567,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Laptop Stand',
    'laptop-stand',
    'An adjustable aluminum laptop stand with ventilation cutouts. Raises screen to eye level for better posture.',
    59.00,
    null,
    null,
    4.6,
    890,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Jogger Pants',
    'jogger-pants',
    'Tapered jogger pants with elastic waistband and zippered pockets. Made from stretch cotton blend for all-day comfort.',
    54.00,
    null,
    null,
    4.2,
    345,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Massage Ball',
    'massage-ball',
    'A textured massage ball for trigger point release and myofascial release. Compact size perfect for travel.',
    16.00,
    null,
    null,
    4.5,
    1234,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Notebook Leather',
    'notebook-leather',
    'A handcrafted leather-bound notebook with refillable paper. Ages beautifully with a rich patina over time.',
    48.00,
    null,
    null,
    4.6,
    289,
    (select id from public.categories where slug = 'productivity'),
    true
  ),
  (
    'Power Bank 20000',
    'power-bank-20000',
    'A high-capacity power bank with 20000mAh and dual USB-C ports. Charges laptops, tablets, and phones simultaneously.',
    59.00,
    null,
    null,
    4.4,
    1567,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Wool Beanie',
    'wool-beanie',
    'A fine-knit merino wool beanie with a folded cuff. Soft, warm, and breathable for cold-weather layering.',
    32.00,
    null,
    null,
    4.3,
    234,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Pull-Up Bar',
    'pull-up-bar',
    'A doorway pull-up bar with multi-grip positions and padded handles. Supports up to 300 lbs with secure locking mechanism.',
    45.00,
    null,
    null,
    4.5,
    890,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Tablet Stand',
    'tablet-stand',
    'A versatile aluminum tablet stand with adjustable viewing angles. Compatible with tablets from 7 to 13 inches.',
    39.00,
    null,
    null,
    4.4,
    567,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Graphic Tee',
    'graphic-tee',
    'A heavyweight cotton graphic tee with a relaxed fit. Pre-shrunk fabric with a soft hand feel.',
    35.00,
    null,
    null,
    4.1,
    456,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Aromatherapy Candle',
    'aromatherapy-candle',
    'A soy wax aromatherapy candle with essential oils of lavender and eucalyptus. Burns cleanly for 50 hours.',
    28.00,
    null,
    null,
    4.6,
    1234,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Ab Roller',
    'ab-roller',
    'An ab roller with knee pad and non-slip grip handles. Targets core muscles for effective abdominal workouts.',
    22.00,
    null,
    null,
    4.3,
    678,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Mouse Wireless',
    'mouse-wireless',
    'A precision wireless mouse with ergonomic curves and silent click technology. Finished in matte black with subtle RGB accent lighting.',
    79.00,
    null,
    null,
    4.7,
    312,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Desk Pad',
    'desk-pad',
    'An extended desk pad with smooth micro-weave surface and non-slip rubber base. Protects your desk and provides ample mouse space.',
    29.00,
    null,
    null,
    4.5,
    890,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Chino Shorts',
    'chino-shorts',
    'Classic chino shorts with a comfortable mid-rise and 9-inch inseam. Stretch cotton twill with belt loops and zippered pockets.',
    58.00,
    null,
    null,
    4.2,
    234,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Hydration Pack',
    'hydration-pack',
    'A lightweight hydration pack with 2-liter reservoir and adjustable straps. Ideal for running, hiking, and cycling.',
    65.00,
    null,
    null,
    4.4,
    567,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Monitor Light Bar',
    'monitor-light-bar',
    'A screen-mounted monitor light bar with adjustable brightness and color temperature. Reduces glare and eye strain.',
    89.00,
    null,
    null,
    4.6,
    789,
    (select id from public.categories where slug = 'office-decor'),
    true
  ),
  (
    'Dress Shirt Slim',
    'dress-shirt-slim',
    'A non-iron slim-fit dress shirt in light blue. Wrinkle-resistant cotton with a spread collar and French cuffs.',
    85.00,
    null,
    null,
    4.3,
    345,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Foam Roller Soft',
    'foam-roller-soft',
    'A soft-density foam roller for gentle muscle recovery and flexibility work. 18 inches long with textured surface.',
    24.00,
    null,
    null,
    4.2,
    456,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Notebook Dot Grid',
    'notebook-dot-grid',
    'A5 dot grid notebook with 160 pages and lay-flat binding. Perfect for bullet journaling and sketching.',
    18.00,
    null,
    null,
    4.5,
    1234,
    (select id from public.categories where slug = 'productivity'),
    true
  ),
  (
    'Wireless Earbuds',
    'wireless-earbuds',
    'Compact true wireless earbuds with deep bass and 24-hour total battery life. IPX5 water resistant for workouts.',
    89.00,
    null,
    null,
    4.4,
    2345,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Bamboo Keyboard',
    'bamboo-keyboard',
    'A slim wireless keyboard with bamboo accents and low-profile keys. Eco-friendly design with multi-device pairing.',
    99.00,
    null,
    'New',
    4.6,
    189,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Wool Cardigan',
    'wool-cardigan',
    'A relaxed-fit merino wool cardigan with horn buttons and patch pockets. Perfect for layering in cooler weather.',
    165.00,
    null,
    null,
    4.7,
    312,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Jump Rope',
    'jump-rope',
    'A professional speed jump rope with ball bearings and adjustable cable length. Lightweight aluminum handles.',
    22.00,
    null,
    null,
    4.4,
    567,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Yoga Block',
    'yoga-block',
    'A high-density EVA foam yoga block with beveled edges. Provides support and stability for deeper stretches.',
    16.00,
    null,
    null,
    4.5,
    890,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Sunglasses Polarized',
    'sunglasses-polarized',
    'Polarized sunglasses with lightweight titanium frame and UV400 protection. Classic aviator style for everyday wear.',
    125.00,
    null,
    null,
    4.3,
    456,
    (select id from public.categories where slug = 'wearables'),
    true
  ),
  (
    'Leather Belt',
    'leather-belt',
    'A full-grain leather belt with brushed silver buckle. Handcrafted with precision stitching and a timeless design.',
    55.00,
    null,
    null,
    4.6,
    789,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Electric Kettle',
    'electric-kettle',
    'A variable temperature electric kettle with hold function and gooseneck spout. Perfect for pour-over coffee and tea.',
    79.00,
    null,
    null,
    4.7,
    1234,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Grip Trainer',
    'grip-trainer',
    'A variable resistance grip trainer with adjustable dial. Builds hand and forearm strength for climbing and daily tasks.',
    19.00,
    null,
    null,
    4.4,
    567,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Laptop Sleeve',
    'laptop-sleeve',
    'A padded neoprene laptop sleeve with faux-fur lining. Protects against scratches and minor bumps with a slim profile.',
    39.00,
    null,
    null,
    4.5,
    890,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Running Shorts',
    'running-shorts',
    'Lightweight running shorts with built-in brief liner and zippered pocket. Moisture-wicking fabric with reflective details.',
    45.00,
    null,
    null,
    4.3,
    345,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Scented Candle',
    'scented-candle',
    'A hand-poured soy wax candle with notes of cedar and bergamot. Housed in a reusable ceramic vessel.',
    32.00,
    null,
    null,
    4.6,
    1234,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Kettlebell 24kg',
    'kettlebell-24kg',
    'A cast iron kettlebell with a smooth powder-coat finish and wide handle. Perfect for advanced strength training.',
    89.00,
    null,
    null,
    4.7,
    456,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Microphone USB',
    'microphone-usb',
    'A professional USB condenser microphone with cardioid pickup pattern and built-in pop filter. Perfect for streaming and podcasting.',
    129.00,
    null,
    null,
    4.8,
    789,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Wool Scarf',
    'wool-scarf',
    'A timeless wool-blend scarf in camel with hand-rolled edges. Generous length for multiple styling options.',
    55.00,
    null,
    null,
    4.3,
    167,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Meditation Bench',
    'meditation-bench',
    'A folding meditation bench with angled seat and padded cushion. Supports comfortable cross-legged sitting.',
    78.00,
    null,
    null,
    4.5,
    234,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Power Bank',
    'power-bank',
    'A compact power bank with 10000mAh capacity and fast charging. Fits easily in pocket or bag for on-the-go charging.',
    29.00,
    null,
    null,
    4.3,
    2345,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Chinos Slim',
    'chinos-slim',
    'A slim-fit chino pant in stone with a comfortable stretch. Modern cut with a mid-rise and straight leg.',
    72.00,
    null,
    null,
    4.4,
    567,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Foam Roller Medium',
    'foam-roller-medium',
    'A medium-density foam roller for general muscle recovery. 18 inches long with a smooth surface.',
    20.00,
    null,
    null,
    4.3,
    890,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Pocket Notebook',
    'pocket-notebook',
    'A compact pocket-sized notebook with 192 pages of dotted paper. Fits in jeans pocket for on-the-go notes.',
    12.00,
    null,
    null,
    4.4,
    1234,
    (select id from public.categories where slug = 'productivity'),
    true
  ),
  (
    'Smart Plug',
    'smart-plug',
    'A Wi-Fi smart plug with energy monitoring and scheduling. Works with Alexa and Google Assistant for voice control.',
    15.00,
    null,
    'Best Seller',
    4.5,
    4567,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Denim Shirt',
    'denim-shirt',
    'A classic denim shirt with a modern fit. Features chest pockets, button closure, and selvedge detail.',
    78.00,
    null,
    null,
    4.2,
    234,
    (select id from public.categories where slug = 'apparel'),
    true
  ),
  (
    'Running Shoes Trail',
    'running-shoes-trail',
    'Trail running shoes with aggressive tread and rock plate protection. Waterproof membrane for all-terrain confidence.',
    149.00,
    null,
    null,
    4.6,
    567,
    (select id from public.categories where slug = 'fitness'),
    true
  ),
  (
    'Tea Set',
    'tea-set',
    'A minimalist ceramic tea set with teapot and four cups. Matte finish in warm white with subtle texture.',
    85.00,
    null,
    null,
    4.7,
    189,
    (select id from public.categories where slug = 'wellness'),
    true
  ),
  (
    'Ergonomic Keyboard',
    'ergonomic-keyboard',
    'A split ergonomic keyboard with adjustable tenting and negative tilt. Reduces wrist strain during long typing sessions.',
    179.00,
    null,
    'New',
    4.6,
    345,
    (select id from public.categories where slug = 'tech-gear'),
    true
  ),
  (
    'Leather Portfolio',
    'leather-portfolio',
    'A luxury leather portfolio with document organizer and tablet sleeve. Handcrafted from full-grain Italian leather.',
    185.00,
    null,
    null,
    4.8,
    234,
    (select id from public.categories where slug = 'productivity'),
    true
  )
on conflict (slug) do nothing;

-- RLS policies (disabled for anon key, enable if using auth)
alter table public.categories disable row level security;
alter table public.products disable row level security;
alter table public.product_variants disable row level security;
