/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c4c7c9",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#b9bcbe",
        "surface-container-low": "#eff4ff",
        "secondary-container": "#86f2e4",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#484c4e",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed": "#00201d",
        "surface-container": "#e6eeff",
        "on-background": "#0d1c2e",
        "secondary-fixed": "#89f5e7",
        outline: "#757684",
        "on-surface": "#0d1c2e",
        "primary-container": "#1e40af",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001453",
        "inverse-on-surface": "#eaf1ff",
        "tertiary-fixed": "#e0e3e5",
        "inverse-surface": "#233144",
        "surface-tint": "#3755c3",
        surface: "#f8f9ff",
        secondary: "#006a61",
        "on-error": "#ffffff",
        "surface-dim": "#ccdbf3",
        "on-secondary-fixed-variant": "#005049",
        "on-secondary": "#ffffff",
        "inverse-primary": "#b8c4ff",
        "primary-fixed-dim": "#b8c4ff",
        tertiary: "#323537",
        primary: "#00288e",
        "on-primary-fixed-variant": "#173bab",
        "on-tertiary": "#ffffff",
        "surface-variant": "#d5e3fc",
        "on-surface-variant": "#444653",
        "on-secondary-container": "#006f66",
        "surface-container-high": "#dce9ff",
        "secondary-fixed-dim": "#6bd8cb",
        background: "#f8f9ff",
        "on-error-container": "#93000a",
        "on-primary-container": "#a8b8ff",
        "on-tertiary-fixed-variant": "#444749",
        "outline-variant": "#c4c5d5",
        "primary-fixed": "#dde1ff",
        "on-tertiary-fixed": "#191c1e",
        "surface-container-highest": "#d5e3fc",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        "container-max": "1280px",
        md: "24px",
        sm: "16px",
        gutter: "24px",
        lg: "40px",
        xs: "8px",
        xl: "64px",
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "display-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
